#pragma once

#define ADOBO_ENGINE_MAX_SPRITES     256
#define ADOBO_ENGINE_MIN_SPRITES     256
#define ADOBO_ENGINE_MIN_ENTITIES2D  256
#define ADOBO_ENGINE_MIN_TEXTURE     12
#define ADOBO_ENGINE_MIN_HITBOXES    4

#define ADOBO_ENGINE_REALLOC_MARGIN  2

#define ADOBO_ENGINE_LOAD_ON_READ    true